### ISSUE TITLE
Crear.php blank page

### ISSUE THREAD

**Issue by superhealing** [mrmalone/ChannelWeb#1]
Hello, i investigated too many hours i still don't understand a few things, might help with a details of contact.

**Comment by mrmalone** [comment]
Did you correctly fill in the config file?

**Comment by superhealing** [comment]
Yes, i did specifically config.php, with corrected permissions, with corrected details even i tried myseft other scripts look connection was right, but i have permission to see querry connection so, every time i press create will connect automatically + drop, that is a good sign the config is properly correct, i tried to enable error_logs thing but i cannot do this.. IF i enable other phps.. like teamspeak and a one that i cannot remember.

**Comment by mrmalone** [comment]
So the robot reaches the server create the channel and then gets the connection lost?

**Comment by superhealing** [comment]
Actually, reach the server and never create a channel, im do again the test.
I actually make a few modifications of that, so i modified where should create(ID) and what group channel id, also i got a thing.. i enabled debug so.

> Notice: Undefined index: SubChannelPass in /srv/www/channel/crear.php on line 13
> 
> Fatal error: Cannot unset $this in /srv/www/channel/Node/Server.php on line 2272

If require i will say what modifications i did made + web + server with that + querry everything, since i cannot do on github, maybe private message or anything like that might help

**Comment by mrmalone** [comment]
I will post these days an upgraded version where there will be no configuration errors, be on the phase.
